sudo: false

notifications:
  email: false

language: node_js

cache:
  yarn: true
  directories:
    - ./elm-stuff
    - ./tests/elm-stuff

before_script:
  - yarn global add create-elm-app
  - make install

script:
  - make build
  - make test
